import { GAME_INTRO, GAME_THUMBNAIL, type Game } from "@/domain/types";
import type { IGamesService } from "./games.interface";

const delay = (ms = 220) => new Promise((resolve) => setTimeout(resolve, ms));

const base = {
  thumbnailUrl: GAME_THUMBNAIL,
  introUrl: GAME_INTRO,
  embedUrl: "",
  isActive: true,
  developer: "DND Studio",
  releasedAt: "2024-04-24T00:00:00.000Z",
  updatedAt: "2026-09-01T00:00:00.000Z",
  playerCount: 20000,
  likeCount: 6100,
  engine: "HTML5",
  platforms: ["browser"],
  orientation: "landscape" as const,
};

const games: Game[] = [
  {
    ...base,
    id: "game-001",
    slug: "farm-valley",
    name: "Farm Valley",
    genre: "simulation",
    rating: 8.7,
    tags: ["simulation", "farm", "casual"],
    collections: ["classic", "quick"],
    description: "Build a cozy pixel farm, plant crops, and grow your valley.",
    featured: true,
    playersLabel: "+1",
  },
  {
    ...base,
    id: "game-002",
    slug: "pixel-karts",
    name: "Pixel Karts",
    genre: "racing",
    rating: 9.1,
    tags: ["racing", "multiplayer", "arcade"],
    collections: ["adrenaline", "friends"],
    description: "Drift through colorful tracks and smash rivals off the road.",
    featured: true,
    playersLabel: "+1",
  },
  {
    ...base,
    id: "game-003",
    slug: "open-front",
    name: "Open Front",
    genre: "strategy",
    rating: 8.4,
    tags: ["strategy", "war", "io"],
    collections: ["brain", "adrenaline"],
    description: "Command units, capture tiles, and outthink the other side.",
    featured: true,
  },
  {
    ...base,
    id: "game-004",
    slug: "keyboard-obby",
    name: "Keyboard Obby",
    genre: "arcade",
    rating: 8.9,
    tags: ["arcade", "obby", "casual"],
    collections: ["meme", "quick"],
    description: "Jump across giant keys and race to the finish line.",
    featured: true,
    playersLabel: "+1",
  },
  {
    ...base,
    id: "game-005",
    slug: "block-world",
    name: "Block World",
    genre: "adventure",
    rating: 8.2,
    tags: ["adventure", "sandbox", "io"],
    collections: ["friends", "classic"],
    description: "Explore a blocky world, build bases, and survive with friends.",
    featured: true,
  },
  {
    ...base,
    id: "game-006",
    slug: "smash-arena",
    name: "Smash Arena",
    genre: "action",
    rating: 8.6,
    tags: ["action", "arena", "multiplayer"],
    collections: ["adrenaline", "friends"],
    description: "Brawl in a tiny arena. Last player standing wins.",
    featured: true,
    playersLabel: "+1",
  },
  {
    ...base,
    id: "game-007",
    slug: "tower-swap",
    name: "Tower Swap",
    genre: "puzzle",
    rating: 8.0,
    tags: ["puzzle", "match", "casual"],
    collections: ["brain", "quick"],
    description: "Swap tiles, clear towers, and chase a high combo score.",
  },
  {
    ...base,
    id: "game-008",
    slug: "idle-forge",
    name: "Idle Forge",
    genre: "clicker",
    rating: 7.9,
    tags: ["clicker", "idle", "simulation"],
    collections: ["quick", "classic"],
    description: "Tap, upgrade, and let the forge run while you are away.",
  },
  {
    ...base,
    id: "game-009",
    slug: "leek-factory",
    name: "Leek Factory",
    genre: "simulation",
    rating: 8.3,
    tags: ["simulation", "tycoon", "casual"],
    collections: ["classic", "brain"],
    description: "Run a chaotic factory and keep the conveyor belts moving.",
  },
  {
    ...base,
    id: "game-010",
    slug: "hero-merge",
    name: "Hero Merge",
    genre: "puzzle",
    rating: 8.1,
    tags: ["puzzle", "merge", "strategy"],
    collections: ["brain", "quick"],
    description: "Merge heroes, unlock new units, and beat each wave.",
  },
  {
    ...base,
    id: "game-011",
    slug: "babel-tower",
    name: "Babel Tower",
    genre: "strategy",
    rating: 8.5,
    tags: ["strategy", "tower-defense"],
    collections: ["brain", "adrenaline"],
    description: "Place towers, time your upgrades, and hold the lane.",
  },
  {
    ...base,
    id: "game-012",
    slug: "mine-clicker",
    name: "Mine Clicker",
    genre: "clicker",
    rating: 7.8,
    tags: ["clicker", "idle"],
    collections: ["quick", "meme"],
    description: "Dig deeper with every tap and unlock new layers of ore.",
  },
  {
    ...base,
    id: "game-013",
    slug: "screw-nuts",
    name: "Screw & Nuts",
    genre: "puzzle",
    rating: 8.8,
    tags: ["puzzle", "relax"],
    collections: ["brain", "classic"],
    description: "Unscrew the right bolts in order and clear the board.",
  },
  {
    ...base,
    id: "game-014",
    slug: "slime-lab",
    name: "Slime Lab",
    genre: "puzzle",
    rating: 8.0,
    tags: ["puzzle", "physics"],
    collections: ["brain", "quick"],
    description: "Guide bouncing slime through pipes without making a mess.",
  },
  {
    ...base,
    id: "game-015",
    slug: "mage-strike",
    name: "Mage Strike",
    genre: "action",
    rating: 8.4,
    tags: ["action", "magic"],
    collections: ["adrenaline", "classic"],
    description: "Cast spells, dodge beams, and climb the wizard ranks.",
  },
  {
    ...base,
    id: "game-016",
    slug: "match-kingdom",
    name: "Match Kingdom",
    genre: "puzzle",
    rating: 8.2,
    tags: ["puzzle", "match-3"],
    collections: ["brain", "classic"],
    description: "Match gems to rebuild a kingdom one combo at a time.",
  },
  {
    ...base,
    id: "game-017",
    slug: "evil-tower",
    name: "Evil Tower",
    genre: "strategy",
    rating: 8.6,
    tags: ["strategy", "tower-defense", "dark"],
    collections: ["adrenaline", "brain"],
    description: "Defend a cursed tower from waves of pixel monsters.",
  },
  {
    ...base,
    id: "game-018",
    slug: "level-100",
    name: "Level 100",
    genre: "adventure",
    rating: 7.7,
    tags: ["adventure", "idle"],
    collections: ["quick", "meme"],
    description: "Climb 100 bite-sized rooms and collect every star.",
  },
  {
    ...base,
    id: "game-019",
    slug: "neon-hopper",
    name: "Neon Hopper",
    genre: "arcade",
    rating: 8.3,
    tags: ["arcade", "jump", "casual"],
    collections: ["quick", "meme"],
    description: "Bounce across neon platforms and chase a new high score.",
  },
  {
    ...base,
    id: "game-020",
    slug: "coin-rush",
    name: "Coin Rush",
    genre: "arcade",
    rating: 8.1,
    tags: ["arcade", "runner"],
    collections: ["quick", "adrenaline"],
    description: "Dash through a coin tunnel and dodge every spike.",
  },
  {
    ...base,
    id: "game-021",
    slug: "space-blob",
    name: "Space Blob",
    genre: "arcade",
    rating: 7.9,
    tags: ["arcade", "space"],
    collections: ["classic", "quick"],
    description: "Pilot a bouncy blob through asteroid fields.",
  },
  {
    ...base,
    id: "game-022",
    slug: "fruit-slice",
    name: "Fruit Slice",
    genre: "arcade",
    rating: 8.5,
    tags: ["arcade", "reflex"],
    collections: ["quick", "classic"],
    description: "Slice falling fruit and keep the combo alive.",
  },
  {
    ...base,
    id: "game-023",
    slug: "blade-dash",
    name: "Blade Dash",
    genre: "action",
    rating: 8.7,
    tags: ["action", "combat"],
    collections: ["adrenaline", "classic"],
    description: "Dash, slash, and clear rooms before the timer hits zero.",
  },
  {
    ...base,
    id: "game-024",
    slug: "night-raid",
    name: "Night Raid",
    genre: "action",
    rating: 8.3,
    tags: ["action", "stealth"],
    collections: ["adrenaline", "brain"],
    description: "Sneak through rooftops and take down pixel guards.",
  },
  {
    ...base,
    id: "game-025",
    slug: "rocket-brawl",
    name: "Rocket Brawl",
    genre: "action",
    rating: 8.8,
    tags: ["action", "arena"],
    collections: ["adrenaline", "friends"],
    description: "Fire rockets in a tiny arena and stay on the last pad.",
    playersLabel: "+1",
  },
  {
    ...base,
    id: "game-026",
    slug: "blob-wars",
    name: "Blob Wars",
    genre: "io",
    rating: 8.4,
    tags: ["io", "multiplayer"],
    collections: ["friends", "adrenaline"],
    description: "Eat smaller blobs, grow fast, and rule the server.",
    featured: true,
    playersLabel: "+1",
  },
  {
    ...base,
    id: "game-027",
    slug: "zone-capture",
    name: "Zone Capture",
    genre: "io",
    rating: 8.2,
    tags: ["io", "territory"],
    collections: ["friends", "brain"],
    description: "Paint the map, cut off rivals, and hold every zone.",
    playersLabel: "+1",
  },
  {
    ...base,
    id: "game-028",
    slug: "dot-siege",
    name: "Dot Siege",
    genre: "io",
    rating: 8.0,
    tags: ["io", "survival"],
    collections: ["adrenaline", "quick"],
    description: "Survive as a tiny dot while the arena shrinks.",
  },
  {
    ...base,
    id: "game-029",
    slug: "agar-lite",
    name: "Agar Lite",
    genre: "io",
    rating: 8.6,
    tags: ["io", "classic"],
    collections: ["classic", "friends"],
    description: "Split, chase, and swallow players in a busy lobby.",
    playersLabel: "+1",
  },
  {
    ...base,
    id: "game-030",
    slug: "hive-clash",
    name: "Hive Clash",
    genre: "io",
    rating: 8.1,
    tags: ["io", "team"],
    collections: ["friends", "adrenaline"],
    description: "Join a hive, swarm the map, and steal the enemy nest.",
    playersLabel: "+1",
  },
  {
    ...base,
    id: "game-031",
    slug: "drift-pixel",
    name: "Drift Pixel",
    genre: "racing",
    rating: 8.8,
    tags: ["racing", "drift"],
    collections: ["adrenaline", "classic"],
    description: "Hold long drifts and rack up score on tight tracks.",
  },
  {
    ...base,
    id: "game-032",
    slug: "turbo-alley",
    name: "Turbo Alley",
    genre: "racing",
    rating: 8.2,
    tags: ["racing", "arcade"],
    collections: ["adrenaline", "quick"],
    description: "Boost through alleys and dodge traffic at full speed.",
  },
  {
    ...base,
    id: "game-033",
    slug: "night-circuit",
    name: "Night Circuit",
    genre: "racing",
    rating: 8.5,
    tags: ["racing", "night"],
    collections: ["adrenaline", "classic"],
    description: "Race neon circuits and beat the ghost lap.",
  },
  {
    ...base,
    id: "game-034",
    slug: "kart-mayhem",
    name: "Kart Mayhem",
    genre: "racing",
    rating: 8.9,
    tags: ["racing", "multiplayer"],
    collections: ["friends", "adrenaline"],
    description: "Throw items, steal first place, and survive the last lap.",
    playersLabel: "+1",
  },
  {
    ...base,
    id: "game-035",
    slug: "pet-cafe",
    name: "Pet Cafe",
    genre: "simulation",
    rating: 8.0,
    tags: ["simulation", "cozy"],
    collections: ["classic", "brain"],
    description: "Serve drinks, care for pets, and grow a tiny cafe.",
  },
  {
    ...base,
    id: "game-036",
    slug: "city-patch",
    name: "City Patch",
    genre: "simulation",
    rating: 8.4,
    tags: ["simulation", "builder"],
    collections: ["brain", "classic"],
    description: "Lay roads, zone districts, and keep the city happy.",
  },
  {
    ...base,
    id: "game-037",
    slug: "bakery-days",
    name: "Bakery Days",
    genre: "simulation",
    rating: 8.1,
    tags: ["simulation", "tycoon"],
    collections: ["classic", "quick"],
    description: "Bake, decorate, and sell out before closing time.",
  },
  {
    ...base,
    id: "game-038",
    slug: "hex-empire",
    name: "Hex Empire",
    genre: "strategy",
    rating: 8.7,
    tags: ["strategy", "hex"],
    collections: ["brain", "classic"],
    description: "Expand hex by hex until the whole map is yours.",
  },
  {
    ...base,
    id: "game-039",
    slug: "card-front",
    name: "Card Front",
    genre: "strategy",
    rating: 8.3,
    tags: ["strategy", "cards"],
    collections: ["brain", "friends"],
    description: "Play cards, counter units, and win the lane war.",
  },
  {
    ...base,
    id: "game-040",
    slug: "pixel-soccer",
    name: "Pixel Soccer",
    genre: "sports",
    rating: 8.6,
    tags: ["sports", "soccer"],
    collections: ["friends", "adrenaline"],
    description: "Score arcade goals in fast two-button matches.",
    featured: true,
    playersLabel: "+1",
  },
  {
    ...base,
    id: "game-041",
    slug: "hoop-street",
    name: "Hoop Street",
    genre: "sports",
    rating: 8.4,
    tags: ["sports", "basketball"],
    collections: ["adrenaline", "quick"],
    description: "Sink threes, dunk, and win the street tournament.",
  },
  {
    ...base,
    id: "game-042",
    slug: "table-tennis-pro",
    name: "Table Tennis Pro",
    genre: "sports",
    rating: 8.1,
    tags: ["sports", "tennis"],
    collections: ["classic", "friends"],
    description: "Time your swings and return every spin serve.",
    playersLabel: "+1",
  },
  {
    ...base,
    id: "game-043",
    slug: "super-slugger",
    name: "Super Slugger",
    genre: "sports",
    rating: 8.0,
    tags: ["sports", "baseball"],
    collections: ["classic", "quick"],
    description: "Hit home runs and steal bases in short innings.",
  },
  {
    ...base,
    id: "game-044",
    slug: "court-kings",
    name: "Court Kings",
    genre: "sports",
    rating: 8.5,
    tags: ["sports", "basketball"],
    collections: ["friends", "adrenaline"],
    description: "Pick a squad and climb the 3v3 court ranks.",
    playersLabel: "+1",
  },
  {
    ...base,
    id: "game-045",
    slug: "cookie-forge",
    name: "Cookie Forge",
    genre: "clicker",
    rating: 7.7,
    tags: ["clicker", "idle"],
    collections: ["quick", "meme"],
    description: "Tap cookies, buy ovens, and watch the dough pile up.",
  },
  {
    ...base,
    id: "game-046",
    slug: "tap-kingdom",
    name: "Tap Kingdom",
    genre: "clicker",
    rating: 8.0,
    tags: ["clicker", "idle"],
    collections: ["quick", "classic"],
    description: "Tap villagers, unlock buildings, and grow a kingdom.",
  },
  {
    ...base,
    id: "game-047",
    slug: "gold-miner-idle",
    name: "Gold Miner Idle",
    genre: "clicker",
    rating: 7.9,
    tags: ["clicker", "idle"],
    collections: ["quick", "meme"],
    description: "Send miners down and cash in every vein of gold.",
  },
  {
    ...base,
    id: "game-048",
    slug: "cave-quest",
    name: "Cave Quest",
    genre: "adventure",
    rating: 8.4,
    tags: ["adventure", "explore"],
    collections: ["classic", "brain"],
    description: "Explore caves, loot relics, and map every secret room.",
  },
  {
    ...base,
    id: "game-049",
    slug: "sky-isles",
    name: "Sky Isles",
    genre: "adventure",
    rating: 8.3,
    tags: ["adventure", "platform"],
    collections: ["classic", "adrenaline"],
    description: "Island-hop through the sky and chase a stolen map.",
  },
  {
    ...base,
    id: "game-050",
    slug: "relic-run",
    name: "Relic Run",
    genre: "adventure",
    rating: 8.1,
    tags: ["adventure", "runner"],
    collections: ["quick", "classic"],
    description: "Sprint temple halls and grab relics before the collapse.",
  },
];

games.forEach((game, index) => {
  game.playerCount = 12000 + index * 4100;
  game.likeCount = 1800 + index * 420;
});

export const createGamesMock = (): IGamesService => ({
  listGames: async (genre) => {
    await delay();
    return genre ? games.filter((game) => game.genre === genre) : games;
  },
  getGame: async (id) => {
    await delay();
    const game = games.find((item) => item.id === id || item.slug === id);
    if (!game) {
      throw new Error("Game not found");
    }
    return game;
  },
});
